# 1. Pandas란?
- 데이터 분석에 특화된 파이썬 라이브러리
- 행과 열로 이루어진 데이터 객체를 만들어 다룰 수 있게 되며, 보다 안정적으로 대용량의 데이터들을 처리하는데 매우 편리한 도구
- Numpy의 확장판으로, `Numpy 기능` + `구조화 된 데이터 처리 기능`을 보유함

## 1-1. Pandas의 주요 데이터 구조

<img src = 'https://dandyrilla.github.io/images/2017-08-12/fig0.png'>

|이름|차원|설명|
|:-----------:|:-----------:|:-----------:|
|Series|1차원|균일한 유형의 배열로 표시된 1차원 데이터|
|DataFrame|2차원|인덱스가 같은 하나 이상의 Series가 모여진 2차원 표 형식의 데이터|

> Pandas의 핵심은 DataFrame!

# 2. DataFrame 생성

## 2-1. 라이브러리 불러오기

In [1]:
import pandas as pd

## 2-2. 데이터프레임 만들기

In [2]:
# 괄호 안에서 Shift + Tab을 눌러보세요!
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

**DataFrame의 속성값**
```python
pd.DataFrame(data = None, index = None, columns = None, dtype = None, copy = False)
```
- data : DataFrame을 생성할 데이터
- index : index에 대한 정보, 미입력시 0부터 순차적으로 부여 (Optional)
- columns : 열에 대한 이름값, 미입력시 0부터 순차적으로 부여 (Optional)
- dtype : 각 column의 데이터 타입 명시, 미입력시 자체적으로 판단 (Optional)

#### [2차원 리스트로 데이터프레임 만들기]

In [3]:
lst = [['권유철', 22, '수학', '', '회장'], 
       ['김진하', 22, '사회', '경제', '교육팀장'],
       ['방서영', 24, '인공', '', '교육팀원'], 
       ['김민아', 23, '컴공', '', '교육팀원'],
       ['조대흠', 22, '영문', '인공', '교육팀원']]

df = pd.DataFrame(lst, columns=['이름', '학번', '전공', '복수전공', '역할'])
df = df.set_index('이름')

df

     학번  전공 복수전공    역할
이름
권유철  22  수학         회장
김진하  22  사회   경제  교육팀장
방서영  24  인공       교육팀원
김민아  23  컴공       교육팀원
조대흠  22  영문   인공  교육팀원

#### [사전으로 데이터프레임 만들기]

In [4]:
dic = {
    '이름': ['권유철', '김진하', '방서영', '김민아', '조대흠'],
    '학번': [22, 22, 24, 23, 22],
    '전공': ['수학', '사회', '인공', '컴공', '영문'],
    '복수전공': ['', '경제', '', '', '인공'],
    '역할': ['회장', '교육팀장', '교육팀원', '교육팀원', '교육팀원']
}

df2 = pd.DataFrame(dic)
df2 = df2.set_index('이름')

df2

     학번  전공 복수전공    역할
이름
권유철  22  수학         회장
김진하  22  사회   경제  교육팀장
방서영  24  인공       교육팀원
김민아  23  컴공       교육팀원
조대흠  22  영문   인공  교육팀원

## 2-3. 데이터프레임 타입 확인

In [5]:
type(df)

pandas.DataFrame

In [6]:
# 컬럼별 데이터 타입 확인
# 각 컬럼은 다양한 데이터 타입으로 구성되며, 같은 컬럼의 데이터 타입은 동일하다
df.dtypes

학번      int64
전공        str
복수전공      str
역할        str
dtype: object

# 3. DataFrame 접근

## 3-1. head, tail로 접근하기

- `head(개수)` : 위에서부터 개수만큼의 데이터 출력
- `tail(개수)` : 밑에서부터 개수만큼의 데이터 출력

In [7]:
df.head(3)

     학번  전공 복수전공    역할
이름
권유철  22  수학         회장
김진하  22  사회   경제  교육팀장
방서영  24  인공       교육팀원

In [8]:
df.tail() #개수를 쓰지 않을 경우 5개만 출력

     학번  전공 복수전공    역할
이름
권유철  22  수학         회장
김진하  22  사회   경제  교육팀장
방서영  24  인공       교육팀원
김민아  23  컴공       교육팀원
조대흠  22  영문   인공  교육팀원

## 3-2. 행명, 열명으로 접근하기: loc
: `df.loc['행명', '열명']`

행: row / 열: column

|접근 방법|사용 방법|
|:--------------------------:|:-----------:|
|행명|`df.loc["row4"]`|
|행명 리스트|`df.loc[["row3", "row4", "row5"]]`|
|행명 슬라이싱|`df["row3" : "row5"]`|
|열명|`df.loc[ : , "col1"]`|`df["col1"]`|
|열명 리스트|`df.loc[ : , ["col3", "col4", "col5"]` or `df[["col3", "col4", "col5"]]`|
|열명 슬라이싱|`df.loc[ : , ["col3" : "col5"]`|

#### [값 1개 인덱싱]

In [9]:
df.loc['권유철', '역할']

'회장'

In [11]:
df[['전공']]

     전공
이름
권유철  수학
김진하  사회
방서영  인공
김민아  컴공
조대흠  영문

#### [한 줄 인덱싱]
- 하나의 index만 조회 할 경우 Series Type으로 출력

In [12]:
# 행명으로 접근하기
# 컬럼 전체를 지정한다는 의미로 : 를 입력함
df.loc['김진하', : ]  # df.loc['김진하']

학번        22
전공        사회
복수전공      경제
역할      교육팀장
Name: 김진하, dtype: object

In [13]:
# 열명으로 접근하기
df.loc[ : , '전공']  #df['전공']  #df.전공

이름
권유철    수학
김진하    사회
방서영    인공
김민아    컴공
조대흠    영문
Name: 전공, dtype: str

#### [여러 줄 인덱싱]
- 여러 index를 조회 할 경우 DataFrame Type으로 출력

In [14]:
df.loc[['방서영', '김민아'], : ]  #df.loc[['방서영', '김민아']]

     학번  전공 복수전공    역할
이름
방서영  24  인공       교육팀원
김민아  23  컴공       교육팀원

In [15]:
df.loc[ : , ['전공', '복수전공']]  #df[['전공', '복수전공']]

     전공 복수전공
이름
권유철  수학
김진하  사회   경제
방서영  인공
김민아  컴공
조대흠  영문   인공

#### [슬라이싱]

In [16]:
df.loc["김진하":"조대흠", : ]  #df.loc['김진하' : '조대흠']  #df['김진하' : '조대흠']

     학번  전공 복수전공    역할
이름
김진하  22  사회   경제  교육팀장
방서영  24  인공       교육팀원
김민아  23  컴공       교육팀원
조대흠  22  영문   인공  교육팀원

In [17]:
df.loc[:, '학번' : '복수전공']

     학번  전공 복수전공
이름
권유철  22  수학
김진하  22  사회   경제
방서영  24  인공
김민아  23  컴공
조대흠  22  영문   인공

## 3-3. 위치 번호로 접근하기: iloc
: `df.iloc['행번호', '열번호']`

|접근 방법|사용 방법|
|:--------------------------:|:-----------:|
|행 위치|`df.iloc[2]`|
|행 위치 리스트|`df.iloc[[2, 6, 4]]`|
|행 위치 슬라이싱|`df.iloc[2:5]` or `df[2:5]`|
|열 위치|`df.iloc[ : , 3]`|
|열 위치 리스트|`df.iloc[ : , [3, 2, 5]]`|
|열 위치 슬라이싱|`df.iloc[ : , 3:5]`|

In [52]:
df

     학번  전공 복수전공    역할
이름
권유철  22  수학         회장
김진하  22  사회   경제  교육팀장
방서영  24  인공       교육팀원
김민아  23  컴공       교육팀원
조대흠  22  영문   인공  교육팀원

#### [0번 row, 3번 column에 해당하는 값 출력]

In [18]:
df.iloc[0, 3]

'회장'

#### [1번과 3번 row, 1번과 2번 column에 해당하는 데이터 출력]

In [20]:
df.iloc[[1,3],[1,2]]

     전공 복수전공
이름
김진하  사회   경제
김민아  컴공

#### [2번 ~ 마지막 row, 0번 ~ 2번 col에 해당하는 데이터 출력]

In [22]:
# 연속된 데이터 출력 --> 슬라이싱 활용

df.iloc[2:, 0:3]

     학번  전공 복수전공
이름
방서영  24  인공
김민아  23  컴공
조대흠  22  영문   인공

### 📌 [과제 12]
12. 프로미스나인 멤버들의 데이터프레임(df)에서 연속된 여러 줄을 찾는 과제입니다.<br/>
    '지원'부터 '지헌'까지의 '학번'과 '역할'만을 확인할 수 있도록 출력해보세요! <br/>
    (인덱싱과 슬라이싱 모두 사용)

In [38]:
import pandas as pd

lst = [['하영', 15, '컴공', 'AI', '회장'], 
       ['지원', 16, '경영', '심리', '교육팀장'],
       ['채영', 17, '경영', '빅사', '교육팀원'], 
       ['나경', 19, '경영', '빅사', '교육팀원'],
       ['지헌', 16, '경제', '빅사', '교육팀원']]

df12 = pd.DataFrame(lst, columns=['이름', '학번', '전공', '복수전공', '역할'])
df12 = df12.set_index('이름')

In [40]:
df12.loc["지원":"지헌",["학번","역할"]]
df12.iloc[1:5,[1,3]]

    전공    역할
이름
지원  경영  교육팀장
채영  경영  교육팀원
나경  경영  교육팀원
지헌  경제  교육팀원

# 4. DataFrame 수정/추가/삭제

## 4-1. 수정

#### [값 1개 수정]

In [44]:
df_new = df.copy()
df_new.loc['권유철', '역할']

'회장'

In [45]:
df_new.loc['권유철', '역할'] = '인싸'
df_new

     학번  전공 복수전공    역할
이름
권유철  22  수학         인싸
김진하  22  사회   경제  교육팀장
방서영  24  인공       교육팀원
김민아  23  컴공       교육팀원
조대흠  22  영문   인공  교육팀원

#### [한 줄 수정]

In [46]:
df_new.loc['김진하'] = [22, '사회', '경제', '교육팀짱']
df_new

     학번  전공 복수전공    역할
이름
권유철  22  수학         인싸
김진하  22  사회   경제  교육팀짱
방서영  24  인공       교육팀원
김민아  23  컴공       교육팀원
조대흠  22  영문   인공  교육팀원

In [48]:
# 역할 column의 모든 값을 동일하게 바꾸기
df_new.loc[ : , '역할'] = '15기'
df_new

     학번  전공 복수전공   역할
이름
권유철  22  수학       15기
김진하  22  사회   경제  15기
방서영  24  인공       15기
김민아  23  컴공       15기
조대흠  22  영문   인공  15기

#### [여러 줄 수정]

In [49]:
df_new.loc[['권유철', '김진하'], '전공'] = "-"
df_new

     학번  전공 복수전공   역할
이름
권유철  22   -       15기
김진하  22   -   경제  15기
방서영  24  인공       15기
김민아  23  컴공       15기
조대흠  22  영문   인공  15기

In [51]:
df_new[['복수전공', '역할']] = "?"
df_new

     학번  전공 복수전공 역할
이름
권유철  22   -    ?  ?
김진하  22   -    ?  ?
방서영  24  인공    ?  ?
김민아  23  컴공    ?  ?
조대흠  22  영문    ?  ?

#### [위치 번호로 값 수정]

In [52]:
df_new.iloc[[0, 1], [2]] = "#"
df_new

     학번  전공 복수전공 역할
이름
권유철  22   -    #  ?
김진하  22   -    #  ?
방서영  24  인공    ?  ?
김민아  23  컴공    ?  ?
조대흠  22  영문    ?  ?

## 4-2. 추가

In [66]:
df_new2 = df.copy()

#### [row 추가]

In [67]:
# 없는 인덱스명으로 데이터를 넣으면, 새로운 row가 추가됨
df_new2.loc['류시현'] = [21, '경영', '', '교육팀원']
df_new2

     학번  전공 복수전공    역할
이름
권유철  22  수학         회장
김진하  22  사회   경제  교육팀장
방서영  24  인공       교육팀원
김민아  23  컴공       교육팀원
조대흠  22  영문   인공  교육팀원
류시현  21  경영       교육팀원

#### [column 추가]

In [68]:
df_new2['기수'] = '15기'
df_new2

     학번  전공 복수전공    역할   기수
이름
권유철  22  수학         회장  15기
김진하  22  사회   경제  교육팀장  15기
방서영  24  인공       교육팀원  15기
김민아  23  컴공       교육팀원  15기
조대흠  22  영문   인공  교육팀원  15기
류시현  21  경영       교육팀원  15기

## 4-3. 삭제
행 방향 axis=0 <br/>
열 방향 axis=1

In [69]:
df_new2.drop('권유철', axis = 0, inplace = True)  #inplace = False --> 기존의 df에 영향 X
df_new2

     학번  전공 복수전공    역할   기수
이름
김진하  22  사회   경제  교육팀장  15기
방서영  24  인공       교육팀원  15기
김민아  23  컴공       교육팀원  15기
조대흠  22  영문   인공  교육팀원  15기
류시현  21  경영       교육팀원  15기

In [70]:
df_new2.drop(['복수전공', '기수'], axis = 1, inplace = True)
df_new2

     학번  전공    역할
이름
김진하  22  사회  교육팀장
방서영  24  인공  교육팀원
김민아  23  컴공  교육팀원
조대흠  22  영문  교육팀원
류시현  21  경영  교육팀원

In [71]:
del df_new2['역할']
df_new2

     학번  전공
이름
김진하  22  사회
방서영  24  인공
김민아  23  컴공
조대흠  22  영문
류시현  21  경영

### 📌 [과제 13]
13. df_new3에 본인 포함 2명의 정보를 추가하고(행), 새로운 열을 만들어보자!

In [80]:
df_new3 = df.copy()
df_new3

     학번  전공 복수전공    역할
이름
권유철  22  수학         회장
김진하  22  사회   경제  교육팀장
방서영  24  인공       교육팀원
김민아  23  컴공       교육팀원
조대흠  22  영문   인공  교육팀원

In [81]:
df_new3.loc["김가연"]=[23, "경영", "빅사", "-"]
df_new3.loc["홍길동"]=[20, "경영", "", "-"]
df_new3["성별"]=["남","여","여","여","남","여","남"]
df_new3

     학번  전공 복수전공    역할 성별
이름
권유철  22  수학         회장  남
김진하  22  사회   경제  교육팀장  여
방서영  24  인공       교육팀원  여
김민아  23  컴공       교육팀원  여
조대흠  22  영문   인공  교육팀원  남
김가연  23  경영   빅사     -  여
홍길동  20  경영          -  남

In [82]:
# 새로운 열 만들기
df_new3['기수']='15기'
df_new3 # 확인

     학번  전공 복수전공    역할 성별   기수
이름
권유철  22  수학         회장  남  15기
김진하  22  사회   경제  교육팀장  여  15기
방서영  24  인공       교육팀원  여  15기
김민아  23  컴공       교육팀원  여  15기
조대흠  22  영문   인공  교육팀원  남  15기
김가연  23  경영   빅사     -  여  15기
홍길동  20  경영          -  남  15기